### ISSUE TITLE
broken svs on Bio-Formats update

### ISSUE THREAD

**Issue by will-moore** [IDR/idr-metadata#691]
When testing https://github.com/ome/omero-web/pull/536 on idr-testing, I noticed this issue which I think Seb mentioned was due to a Bio-Formats update:

Deployed on idr-testing from branch at #537, this is returning different `zoomLevelScaling` from previously!?
On https://idr.openmicroscopy.org/webclient/img_detail/9840218/ that image has:

```
    "tiles": true,
    "tile_size": {
        "width": 240,
        "height": 240
    },
    "levels": 3,
    "zoomLevelScaling": {
        "0": 1.0,
        "1": 0.2499840367792606,
        "2": 0.029308473277568484
    },
```

But on idr-testing, a different zoomLevelScaling is causing problems:

![Screenshot 2024-02-28 at 13 40 52](https://github.com/ome/omero-web/assets/900055/9cab7216-28be-447d-92ac-3751836fc68f)

**Comment by will-moore** [comment]
As discussed in IDR meeting:
 - need to fix by re-importing (will get 2 images instead of 3) and re-annotate.
 - need to check for other images with this issue - find other svs images and check manually

**Comment by will-moore** [comment]
Find 'SVS' format and count images...
```
idr=> select * from format where value='SVS';
 id  | permissions | value | external_id 
-----+-------------+-------+-------------
 360 |         -52 | SVS   |            
(1 row)

idr=> select count(*) from image where format=360 and series=1;
 count 
-------
   556
(1 row)
```

Find Datasets...
```
idr=> select DISTINCT parent from DatasetImageLink where child in (select id from image where format=360 and series=1);
 parent 
--------
  10348
  10349
  10352
  10354
  10356
  10358
  10388
  10413
  10414
  10415
  10425
  10426
  10427
  10428
  10429
  10431
  10436
  10450
  10461
  10474
  10475
  10476
  10478
  10479
  10480
  10481
  10484
  10485
  10492
  10517
  10530
  10550
  10557
  10558
  10559
  10560
  15274
  15280
  16651
  16652
  16653
  16654
(42 rows)
```

**Comment by will-moore** [comment]
All the svs above are from idr0070. The https://github.com/IDR/idr0070-kerwin-hdbr/blob/master/experimentA/idr0070-experimentA-filePaths.tsv has 400 svs images, so let's just re-import all of them.

Steps:
 - Delete all existing svs images from idr0070
 - Re-import svs images
 - Update https://github.com/IDR/idr0070-kerwin-hdbr/blob/master/experimentA/idr0070-experimentA-annotation.csv to remove the 400 'label' images
 - Re-annotate svs images (maybe re-annotate ALL images will be easier)

**Comment by will-moore** [comment]
Test deleting even a single Image fails (hangs) due to Annotations.
First remove all annotations...

```
$  omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/organism", "openmicroscopy.org/mapr/antibody", "openmicroscopy.org/mapr/gene", "openmicroscopy.org/mapr/cell_line", "openmicroscopy.org/mapr/phenotype", "openmicroscopy.org/mapr/sirna", "openmicroscopy.org/mapr/compound", "openmicroscopy.org/mapr/protein"], "typesToIgnore":["Annotation"]}' --cfg experimentA/idr0070-experimentA-bulkmap-config.yml Project:1104

$ omero metadata populate --context deletemap --report --wait 300 --batch 100 --cfg experimentA/idr0070-experimentA-bulkmap-config.yml Project:1104

$ python /uod/idr/metadata/idr-utils/scripts/annotate/clean_orphaned_maps.py
INFO:omero.util.Resources:Starting
INFO:omero.util.Resources:Starting
INFO:omero.util.Resources:Halted
INFO:root:Found 0 orphaned Organism maps
INFO:root:Found 74 orphaned Antibody maps
INFO:root:Deleting 74 maps
INFO:root:Found 2 orphaned Gene maps
INFO:root:Deleting 2 maps
INFO:root:Found 0 orphaned Cell Line maps
INFO:root:Found 0 orphaned Phenotype maps
INFO:root:Found 0 orphaned siRNA maps
INFO:root:Found 0 orphaned Compound maps
INFO:root:Found 0 orphaned Protein maps
INFO:root:Found 0 orphaned Notebook maps
INFO:root:Found 0 orphaned Study Info maps
INFO:root:Found 0 orphaned Study Components maps
INFO:omero.util.Resources:Halted
```
Can't delete using a single Image:ID:
```
$ omero delete --dry-run --report Image:9838978
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
omero.cmd.Delete2 Image:9838978 failed: 'graph-fail'
failed: within Fileset[3550638] may not delete Image[9838978] while Image[9838979] remains
Steps: 4
Elapsed time: 0.844 secs.
Flags: [FAILURE, CANCELLED]
```
Need to use Fileset ID:
```
$ omero delete --dry-run --report Fileset:3550638
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
omero.cmd.Delete2 Fileset:3550638 Dry run performed
ok
Steps: 4
Elapsed time: 5.382 secs.
Flags: []
Deleted objects
  Instrument:93241
  Objective:90855
  ObjectiveSettings:91280-91282
  CommentAnnotation:25123922
  FilesetAnnotationLink:3550438
  DatasetImageLink:4540977-4540979
  Channel:26299350-26299358
  Image:9838977-9838979
  LogicalChannel:10609300-10609308
  OriginalFile:29671051,29671052
  Pixels:9838977-9838979
  ChannelBinding:25422660-25422668
  QuantumDef:9523332-9523334
  RenderingDef:9523332-9523334
  Thumbnail:11390582-11390584
  Fileset:3550638
  FilesetEntry:22140458
  FilesetJobLink:14306936-14306940
  IndexingJob:14317104
  JobOriginalFileLink:3568052
  MetadataImportJob:14317101
  PixelDataJob:14317102
  ThumbnailGenerationJob:14317103
  UploadJob:14317100
```


Max Fileset ID for idr0070 is 3552155

```
psql -U omero -d idr -h $DBHOST -c "select count(fileset) from image where format=360 and series=1 and (fileset < 3552156)"
 count 
-------
   400
(1 row)
```

Get Fileset IDs....
```
psql -U omero -d idr -h $DBHOST -c "select fileset from image where format=360 and series=1 and (fileset < 3552156)" >> idr0070_svs_filesetIds.txt
```
Need to remove whitespace from each line:
```
$ for r in $(cat idr0070_svs_filesetIds.txt); do echo $r | tr -d '[:space:]' >> idr0070_svs_filesetIds.csv && echo "" >> idr0070_svs_filesetIds.csv; done
```

Do the delete....
```
for r in $(cat idr0070_svs_filesetIds.csv); do omero delete --report Fileset:$r; done
```

**Comment by will-moore** [comment]
Now re-import....

```
sudo cat idr0070-experimentA-filePaths.tsv | grep svs >> /tmp/idr0070-experimentA-filePaths_svs.tsv
sudo mv /tmp/idr0070-experimentA-filePaths_svs.tsv ./
sudo vi idr0070-experimentA-bulk.yml
```
As omero-server...

```
omero import --bulk experimentA/idr0070-experimentA-bulk.yml --file /tmp/idr0070svs.log  --errs /tmp/idr0070svs.err
```

log - seeing some svs not imported because original wasn't deleted...
```
2024-03-27 16:44:56,417 6461       [2-thread-1] INFO   .importer.exclusions.ClientPathExclusion - ClientPath match for filename: uod/idr/filesets/idr0070-kerwin-hdbr/20200414-Batch3-ftp/HDBR_SYP_IHC/1605,2,Rt hemi,10pcw,24_SYP.svs
```

**Comment by will-moore** [comment]
Re-annotate....

Remove label rows from csv on idr-testing...

```
[wmoore@test120-omeroreadwrite experimentA]$ sudo cat idr0070-experimentA-annotation.csv | grep -v label > /tmp/idr0070-experimentA-annotation2.csv
[wmoore@test120-omeroreadwrite experimentA]$ sudo rm idr0070-experimentA-annotation.csv
[wmoore@test120-omeroreadwrite experimentA]$ sudo mv /tmp/idr0070-experimentA-annotation2.csv idr0070-experimentA-annotation.csv
```
Reannotate as normal... check_annotations....

````
/opt/omero/server/venv3/bin/python /uod/idr/metadata/idr-utils/scripts/annotate/check_annotations.py Project:1104 idr0070-experimentA-annotation.csv --output /tmp/errors.csv


GAP43-10PCW,"HDBR_GAP43_IHC_10PCW/1634,6,Sl 2,10pcw,37_GAP43.svs",,,,,,,,,,,,,,,,,,,,Missing annotation
GAP43-12PCW,"HDBR_GAP43_IHC_12PCW/11761,12,Sl 3,12pcw,140_GAP43.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation
GAP43-CS18,"HDBR_GAP43_IHC_CS18/1262,2,Embryo_Placenta,CS18,165_GAP43.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation
MKI67-10PCW,"HDBR_MKI67_IHC/1634,6,Sl 2,10pcw,37_KI67.svs",,,,,,,,,,,,,,,,,,,,Missing annotation
NKX2-2-CS19,"HDBR_NKX2-2_IHC_CS19/352,1,Head,CS19,284_NKX2-2.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation
PAX6-12PCW,"HDBR_PAX6_IHC_hires_12PCW/11610,9,brain,12pcw,114_PAX6.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation
PAX6-CS19,"HDBR_PAX6_IHC_hires_CS19/352,1,Head,CS19,284_PAX6.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation
WNT8B-12PCW,"HDBR_WNT8B_IHC_12PCW/11610,9,brain,12pcw,110_2014-05-20 14_35_30_wnt8b.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation
WNT8B-12PCW,"HDBR_WNT8B_IHC_12PCW/11610,9,brain,12pcw,160_2014-05-20 14_17_11_wnt8b.svs [label image]",,,,,,,,,,,,,,,,,,,,Missing annotation

```

**Comment by will-moore** [comment]
`Missing annotation` errors from above are fixed in https://github.com/IDR/idr0070-kerwin-hdbr/pull/2/commits/4b08e7f99036f34cdd02ddb1f8bcf7ba6c885c3e as follows:

Checked all 7 of the `[label image]` images above and they are all working. So these are genuine label images and should be added back to the `annotations.csv`.
The other 2 `Missing annotation` errors are from 2 images that are now just a single image (no `[. ]` in the name) so these were re-named in the `annotations.csv`.

**Comment by will-moore** [comment]
Fixed - test:
```
(venv3) bash-4.2$ /opt/omero/server/venv3/bin/python /uod/idr/metadata/idr-utils/scripts/annotate/check_annotations.py Project:1104 idr0070-experimentA-annotation.csv --output /tmp/idr0070_errors.csv
All images are unique and have annotations.
```

Deleted previous OMERO.table:
```
(venv3) bash-4.2$ omero delete --report Annotation:25135328
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
omero.cmd.Delete2 Annotation:25135328 ok
Steps: 6
Elapsed time: 0.248 secs.
Flags: []
Deleted objects
  FileAnnotation:25135328
  ProjectAnnotationLink:1667
  OriginalFile:29676048
```

Create OMERO.table
```
/opt/omero/server/OMERO.server/bin/omero metadata populate --report --batch 1000 --file idr0070-experimentA-annotation.csv Project:1104
```

Create Map annotations
```
/opt/omero/server/OMERO.server/bin/omero metadata populate --context bulkmap --batch 100 --cfg idr0070-experimentA-bulkmap-config.yml Project:1104
```

**Comment by will-moore** [comment]
The 3 Filesets in https://idr-testing.openmicroscopy.org/webclient/?show=dataset-10461 are still broken.
These weren't deleted & reimported for some reason...?

Fileset IDs are:
3551354, 3551355, 3551356

These are all found in `idr0070_svs_filesetIds.csv` above. So delete was attempted above.
Try again:

```
(venv3) bash-4.2$ omero delete Fileset:3551354 --report
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
omero.cmd.Delete2 Fileset:3551354 failed: 'graph-fail'
failed: cannot read ome.model.fs.Fileset[3551354]
Steps: 6
Elapsed time: 0.032 secs.
Flags: [FAILURE, CANCELLED]
```

Also, none of these Filesets or Image IDs can be found in the DB via psql.
Using the Dataset ID, can see it contains different Images:

```
idr=> select * from DatasetImageLink where parent=10461;
   id    | permissions | version |  child   | creation_id | external_id | group_id | owner_id | update_id | parent 
---------+-------------+---------+----------+-------------+-------------+----------+----------+-----------+--------
 7310578 |         -56 |       0 | 15153328 |   389349671 |             |        3 |        2 | 389349671 |  10461
 7310579 |         -56 |       0 | 15153329 |   389349671 |             |        3 |        2 | 389349671 |  10461
 7310580 |         -56 |       0 | 15153330 |   389349700 |             |        3 |        2 | 389349700 |  10461
 7310581 |         -56 |       0 | 15153331 |   389349700 |             |        3 |        2 | 389349700 |  10461
 7310582 |         -56 |       0 | 15153332 |   389349731 |             |        3 |        2 | 389349731 |  10461
 7310583 |         -56 |       0 | 15153333 |   389349731 |             |        3 |        2 | 389349731 |  10461
(6 rows)
```

It turns out that the images, thumbnails, right panel etc showing in the webclient above were all cached in the browser or nginx and have all been deleted and replaced successfully!

**Comment by will-moore** [comment]
cc @francesw or @dominikl 

I wonder if you could review the actions above that I have performed on idr-testing (starting at https://github.com/IDR/idr-metadata/issues/691#issuecomment-2023174883 above) and plan to apply to idr-next for the NGFF release?

Summary:
 - removed all annotations for idr0070
 - deleted and re-imported all svs images in idr0070 (400 in total)
 - updated annotations.csv accordingly (mostly just removing `[macro]` rows but some other tweaks too - see https://github.com/IDR/idr0070-kerwin-hdbr/pull/2
 - checked and re-apply annotations
 
You can see an example of the changes by looking at e.g.
https://idr.openmicroscopy.org/webclient/?show=dataset-10461
(and the equivalent Dataset on idr testing)

**Comment by will-moore** [comment]
Final test on `pilot-idrngff`...

```
psql -U omero -d idr -h $DBHOST -c "select fileset from image where format=360 and series=1 and (fileset < 3552156)" >> idr0070_svs_filesetIds.txt

$ for r in $(cat idr0070_svs_filesetIds.txt); do echo $r | tr -d '[:space:]' >> idr0070_svs_filesetIds.csv && echo "" >> idr0070_svs_filesetIds.csv; done

# remove first and last (non-ID) rows
vi idr0070_svs_filesetIds.csv

(venv3) bash-5.1$ wc !$
wc idr0070_svs_filesetIds.csv
 400  400 3200 idr0070_svs_filesetIds.csv

omero login

# start 10:18...
for r in $(cat idr0070_svs_filesetIds.csv); do echo $r && omero delete Fileset:$r; done

**Comment by dominikl** [comment]
👍 Looks good to me!

**Comment by will-moore** [comment]
Import on `pilot-idrngff` above is failing with...

```
2024-04-25 10:33:34,114 4435       [      main] INFO          ome.formats.importer.ImportConfig - OMERO.blitz Version: 5.7.1
2024-04-25 10:33:34,288 4609       [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 7.0.0 revision: 3f8b3326cb578d59bd948fb84c838ff77e9f1b08 date: 1 August 2023
2024-04-25 10:33:34,693 5014       [      main] INFO   formats.importer.cli.CommandLineImporter - Setting checksum algorithm to File-Size-64
2024-04-25 10:33:34,694 5015       [      main] INFO   formats.importer.cli.CommandLineImporter - Skipping minimum/maximum computation
2024-04-25 10:33:34,694 5015       [      main] INFO   formats.importer.cli.CommandLineImporter - Setting transfer to ln_s
2024-04-25 10:33:34,697 5018       [      main] INFO   formats.importer.cli.CommandLineImporter - Adding exclusion: clientpath
2024-04-25 10:33:35,087 5408       [      main] INFO   formats.importer.cli.CommandLineImporter - Setting parallel upload: 8
2024-04-25 10:33:35,088 5409       [      main] INFO   formats.importer.cli.CommandLineImporter - Log levels -- Bio-Formats: ERROR OMERO.importer: INFO
2024-04-25 10:33:42,061 12382      [      main] INFO      ome.formats.importer.ImportCandidates - Depth: 4 Metadata Level: MINIMUM
2024-04-25 10:33:43,438 13759      [      main] ERROR     ome.formats.importer.cli.ErrorHandler - FILE_EXCEPTION: /uod/idr/filesets/idr0070-kerwin-hdbr/20200414-Batch3-ftp/HDBR_SYP_IHC/11610,9,brain,12pcw,97_SYP.svs
java.lang.Exception: java.lang.NoSuchMethodError: 'java.lang.Object loci.formats.CoreMetadataList.remove(int, int)'
        at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:469)
        at ome.formats.importer.ImportCandidates.handleFile(ImportCandidates.java:576)
        at ome.formats.importer.ImportCandidates.execute(ImportCandidates.java:384)
        at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:222)
        at ome.formats.importer.ImportCandidates.<init>(ImportCandidates.java:174)
        at ome.formats.importer.cli.CommandLineImporter.<init>(CommandLineImporter.java:148)
        at ome.formats.importer.cli.CommandLineImporter.main(CommandLineImporter.java:1021)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object loci.formats.CoreMetadataList.remove(int, int)'
        at loci.formats.in.SVSReader.initStandardMetadata(SVSReader.java:652)
        at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98)
        at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:610)
        at loci.formats.FormatReader.setId(FormatReader.java:1466)
        at loci.formats.ImageReader.setId(ImageReader.java:863)
        at ome.formats.importer.OMEROWrapper$4.setId(OMEROWrapper.java:167)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:660)
        at loci.formats.ChannelFiller.setId(ChannelFiller.java:234)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:660)
        at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:293)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:660)
        at loci.formats.Memoizer.setId(Memoizer.java:698)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:660)
        at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:427)
        ... 6 common frames omitted
2024-04-25 10:33:43,440 13761      [      main] INFO      ome.formats.importer.ImportCandidates - 1 file(s) parsed into 0 group(s) with 1 call(s) to setId in 1336ms. (1380ms total) [0 unknowns]
2024-04-25 10:33:47,596 17917      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Attempting initial SSL connection to localhost:4064
2024-04-25 10:33:55,775 26096      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Insecure connection requested, falling back
2024-04-25 10:34:00,118 30439      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Pinging session every 300s.
2024-04-25 10:34:00,135 30456      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Server: 5.6.9
2024-04-25 10:34:00,136 30457      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Client: 5.7.1
2024-04-25 10:34:00,136 30457      [      main] INFO       ome.formats.OMEROMetadataStoreClient - Java Version: 11.0.22
2024-04-25 10:34:00,136 30457      [      main] INFO       ome.formats.OMEROMetadataStoreClient - OS Name: Linux
2024-04-25 10:34:00,136 30457      [      main] INFO       ome.formats.OMEROMetadataStoreClient - OS Arch: amd64
2024-04-25 10:34:00,136 30457      [      main] INFO       ome.formats.OMEROMetadataStoreClient - OS Version: 5.14.0-362.24.1.el9_3.0.1.x86_64
No imports due to errors!
```

**Comment by will-moore** [comment]
Try import again.. after [updating jars](https://github.com/IDR/idr-metadata/issues/675#issuecomment-2077639689)
```
omero import --bulk experimentA/idr0070-experimentA-bulk.yml --file /tmp/idr0070svs_2.log  --errs /tmp/idr0070svs_2.err
```
Seems to be working!!

**Comment by will-moore** [comment]
Import complete...
Checkout the updated annotations.csv from https://github.com/IDR/idr0070-kerwin-hdbr/pull/2

```
(base) [wmoore@pilot-idrngff-omeroreadwrite idr0070-kerwin-hdbr]$ sudo -Es git checkout will/label_images_removal
M	experimentA/idr0070-experimentA-bulk.yml
HEAD is now at 4b08e7f Fix annotations.csv for [label image] images
```
as omero-server
```
(venv3) bash-5.1$ /opt/omero/server/venv3/bin/python /uod/idr/metadata/idr-utils/scripts/annotate/check_annotations.py Project:1104 idr0070-experimentA-annotation.csv --output /tmp/idr0070_errors.csv
All images are unique and have annotations.


$ omero delete --report Annotation:25135328
Previous session expired for demo on localhost:4064
Server: [localhost:4064]
Username: [demo]
Password:
Created session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
omero.cmd.Delete2 Annotation:25135328 ok
Steps: 6
Elapsed time: 0.492 secs.
Flags: []
Deleted objects
  FileAnnotation:25135328
  ProjectAnnotationLink:1667
  OriginalFile:29676048


/opt/omero/server/OMERO.server/bin/omero metadata populate --report --batch 1000 --file idr0070-experimentA-annotation.csv Project:1104

/opt/omero/server/OMERO.server/bin/omero metadata populate --context bulkmap --batch 100 --cfg idr0070-experimentA-bulkmap-config.yml Project:1104
